# Generated by Django 4.1.3 on 2022-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.statustask', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.typetask', verbose_name='Тип'),
        ),
    ]
