# Generated by Django 4.1.3 on 2022-11-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_status_alter_task_type_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_task',
        ),
        migrations.AddField(
            model_name='task',
            name='type_task',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='webapp.typetask'),
        ),
    ]
