# Generated by Django 4.1.3 on 2022-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_task_type_task_task_type_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(default=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, default=True, null=True, verbose_name='Дата окончания')),
            ],
        ),
    ]
