# Generated by Django 4.1.3 on 2022-12-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_projecttask_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={'permissions': [('сan_add_user', 'Может добавлять пользователя'), ('сan_change_user', 'Может изменять пользователя'), ('сan_delete_user', 'Может удалять пользователя')]},
        ),
    ]
