# Generated by Django 4.1.3 on 2023-01-11 20:51

from django.db import migrations



def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_birth_date_remove_profile_link_and_more'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop)
    ]
